title: leavenipm Intern
description: AI × 法律新創實習基地
baseurl: "/leavenipm-intern" 
url: "https://leaven-ipm-ai-team.github.io/"

theme: minima
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:name/
